# Generated by Django 5.0.6 on 2024-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fcm_token',
            field=models.CharField(blank=True, default='n/a', max_length=255, null=True),
        ),
    ]
