# Generated by Django 5.0.6 on 2024-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='Dynamic_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/qrcodes_PAYMENTS/'),
        ),
    ]
