# Generated by Django 5.0.6 on 2024-09-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('businesses', '0003_business_dynamic_qr_code'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport_Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='static/img/qrcodes/')),
                ('Dynamic_qr_code', models.ImageField(blank=True, null=True, upload_to='static/img/qrcodes_PAYMENTS/')),
                ('corridor', models.CharField(max_length=100)),
                ('fcm_token', models.CharField(blank=True, default='n/a', max_length=255, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.payscanuser')),
            ],
        ),
    ]
