# Generated by Django 5.0.6 on 2024-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_transport_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport_business',
            name='corridor',
        ),
        migrations.AddField(
            model_name='transport_business',
            name='corridorA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport_business',
            name='corridorB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
