# Generated by Django 5.0.6 on 2024-09-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_remove_transport_business_corridor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport_business',
            old_name='corridorA',
            new_name='corridor',
        ),
        migrations.RemoveField(
            model_name='transport_business',
            name='corridorB',
        ),
    ]
