# Generated by Django 5.0.6 on 2024-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_rename_corridora_transport_business_corridor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='corridor',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Transport_Business',
        ),
    ]
