# Generated by Django 5.0.6 on 2024-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_business_corridor_delete_transport_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='number_plate',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
