# Generated by Django 5.0 on 2024-10-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_business_number_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='public_transport',
            field=models.BooleanField(default=1),
        ),
    ]
