# Generated by Django 5.0.6 on 2024-08-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
