# Generated by Django 5.0.6 on 2024-08-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payscan', '0002_business_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/qrcodes/'),
        ),
    ]
