# Generated by Django 5.0.6 on 2024-08-09 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payscan', '0003_alter_business_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payscan.agent'),
        ),
    ]
