# Generated by Django 5.0.6 on 2024-08-15 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('businesses', '0001_initial'),
        ('payscan', '0004_alter_transaction_agent'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='agent',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.RemoveField(
            model_name='business',
            name='owner',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to='businesses.business'),
        ),
        migrations.RemoveField(
            model_name='payscanuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='users.payscanuser'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='PayscanUser',
        ),
    ]
