"""
Django settings for payscan project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mnfxx8wt#p8q03e-&h!y6ud=c(r9&5@^$0$$)ez32o*&!js17l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'twilio',
    'axes',
    'payscan',
    'agents',
    'businesses',
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Axes must be first
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]



ROOT_URLCONF = 'payscan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            
        },
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

WSGI_APPLICATION = 'payscan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
'ENGINE': 'django.db.backends.mysql',
'NAME': 'softlabe_payscandb',
'USER': 'root',
'PASSWORD': '',
'HOST': 'localhost', # Or an IP Address that your DB is hosted on
'PORT': '3306',}
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
   
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
 
    {
        'NAME': 'businesses.validators.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# settings.py
TIME_ZONE = 'Africa/Johannesburg'
USE_TZ = True
USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'payscan/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'payscan/static')]

LOGIN_REDIRECT_URL='/afterlogin'
LOGIN_URL = 'login'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security settings
#SECURE_HSTS_SECONDS = 31536000 # 1 year
#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECRET_KEY = 'randomly_generated_secret_key'
#SECURE_HSTS_PRELOAD = True

# Axes configuration
AXES_FAILURE_LIMIT = 5  # Number of allowed attempts
AXES_COOLOFF_TIME = 1  # Cool-off period in hours
AXES_RESET_ON_SUCCESS = True  # Reset attempts on successful login

SITE_URL = 'http://127.0.0.1:8000/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print("Base Directory:", BASE_DIR)
print("Static Root:", STATIC_ROOT)
print("Media Root:", MEDIA_ROOT)

#settings.py MOMO API
MTN_MOMO_API_KEY = 'a0b02d7e798c4b48809406432e9a5d18'
MTN_MOMO_ACCESS_TOKEN='eyJ0eXAiOiJKV1QiLCJhbGciOiJSMjU2In0.eyJjbGllbnRJZCI6IjE4ODA0NjVlLTc5ZGYtNDhlNS05MDgxLTdjMDI3OGI0Y2Q4NyIsImV4cGlyZXMiOiIyMDI0LTA5LTE2VDE4OjE0OjM4LjUwNSIsInNlc3Npb25JZCI6ImNhNzJhY2NiLTdkODktNGMxMC04MTY1LTM2ODJlZmRhYmU5NCJ9.HBH5uC2Z0FuuR4A-Pcfqc9_U3iXM9fmeRDvOHJGZCQ9-WJi2hxEH_1tY37t4ge2NZN55tLHitnd_Wt17zPJ8jF2feDhmr7zmMo-hm-El8NMpV1zM9EME8CrTGX5SavJYFEkNpjPhtvPb2J4RlQPas2WOMTZxIfIoUnU0RbB799sIELf41ulWe1-AeGZYlzL2hI_s7Me7r_hzhFf0TEfSCrwLlw6eMfp3qtWOaasAQ7EFR20_zFOlh-e2Z13OoXXRg_JO4XzWtyegaLLgFjGt4qnnTbE0gVB9oSuRRghxo2iCVYwBwW952mUT2oH42LBVOwR1xdITQ_b9KlzwfDKPSg'
MTN_MOMO_SUBSCRIPTION_KEY='9c990bd1b3914fb783317a44c4971c62'
MOMO_API_ENVIRONMENT = 'sandbox'  # or 'live'     






TWILIO_ACCOUNT_ID=''
TWILIO_AUTH_TOKEN=''
TWILIO_DEFAULT_CALLERID=''
DJANGO_TWILIO_FORGERY_PROTECTION=False




{
  "python.analysis.extraPaths": [
    "E:/projects/payscans/payscan_WEB-main/payscan/.venv/Lib/site-packages"
  ]
}
